# Generated by Django 4.2.1 on 2023-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0002_alter_producto_en_promocion_alter_producto_en_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_Basico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_pedido', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('horario_entrega', models.CharField(max_length=100)),
                ('detalle_pedido', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
