# Generated by Django 4.2.1 on 2023-06-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0004_alter_pedido_basico_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('titulo_promo', models.CharField(max_length=100)),
                ('descripcion_promo', models.TextField()),
                ('precio_promo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado_promo', models.CharField(max_length=50)),
            ],
        ),
    ]
