# Generated by Django 4.2.1 on 2023-06-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0008_alter_promocion_imagen_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='imagen_promo',
        ),
        migrations.AddField(
            model_name='promocion',
            name='incluir_imagen_promo',
            field=models.BooleanField(default=True),
        ),
    ]
