# Generated by Django 4.2.1 on 2023-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0009_remove_promocion_imagen_promo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen_promo',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
