# Generated by Django 4.2.1 on 2023-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0010_promocion_imagen_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='incluir_imagen_promo',
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagen_promo',
            field=models.ImageField(blank=True, upload_to='imagenes_promo/'),
        ),
    ]
