# Generated by Django 4.2.1 on 2023-06-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0011_remove_promocion_incluir_imagen_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='imagen_promo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_promo/'),
        ),
    ]
