# Generated by Django 4.2.1 on 2023-06-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0013_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-fecha_comentario']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_Comentario',
            new_name='fecha_comentario',
        ),
    ]
