# Generated by Django 4.2.1 on 2023-06-24 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0015_remove_comentario_user_comentario_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
