# Generated by Django 4.2.1 on 2023-06-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCorrea', '0016_comentario_apellido_alter_comentario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_pedido', models.CharField(max_length=100)),
                ('fecha_pedido', models.DateField()),
                ('horario_entrega', models.CharField(max_length=100)),
                ('detalle_pedido', models.TextField()),
                ('estado_pedido', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
    ]
