# Generated by Django 4.2.1 on 2023-06-25 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppCorrea', '0017_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField()),
                ('horario_entrega', models.CharField(max_length=100)),
                ('lugar_entrega', models.CharField(max_length=100)),
                ('estado_pedido', models.CharField(default='Pendiente', max_length=50)),
                ('detalle_pedido', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
